### ISSUE TITLE
Can you add the ability to change the GraphWin icon?

### ISSUE THREAD

**Issue by JohnMackYouTube05** [bbrzuszk/pythonGraphics#30]
Hello,

Is there a way to change the icon that shows up in the title bar to any other image? Currently it just shows up as a feather, or quill of some sort, and I don't want to mess with my own graphics.py file copy to try and add a `tk.iconphoto` option to the GraphWin class, in fear of breaking the file. Can anyone try to add icon changing abilities?

Thanks,
John McNamara

**Comment by bbrzuszk** [comment]
Done, new graphwin method def setWindowIcon(self, path): to give this ability.  Not published in wiki yet

**Comment by JohnMackYouTube05** [comment]
Thanks! Now we can set icons for our games!
